### ISSUE TITLE
什么是目录管理功能？

### ISSUE THREAD

**Issue by ghost** [zer0Black/zer0Blog#2]

**Comment by zer0Black** [comment]
可以给博客 打标签（tag） 和 分到某个目录 比如分到 编程语言 目录。或者 职场规划 目录

**Comment by ghost** [comment]
类似于专题？这应该是允许用户自定义添加的，比如简书的文集功能。为什么说应该一开始就设定不变呢？

**Comment by zer0Black** [comment]
你说的没错。其实用户动态添加是应该的。不过我这个博客是给公司内部用的。犯懒就没写。不过这个东西需要用的人写一下也简单。

**Comment by ghost** [comment]
嗯，原来如此。只是不理解所以问一下。谢谢了。
